-- Stable source identity and change tracking for incremental RAG updates.

ALTER TABLE public.rag_hr_embeddings
    ADD COLUMN IF NOT EXISTS source_type VARCHAR(64),
    ADD COLUMN IF NOT EXISTS source_id TEXT,
    ADD COLUMN IF NOT EXISTS content_hash CHAR(64),
    ADD COLUMN IF NOT EXISTS indexed_at TIMESTAMPTZ;

ALTER TABLE public.rag_job_embeddings
    ADD COLUMN IF NOT EXISTS source_type VARCHAR(64),
    ADD COLUMN IF NOT EXISTS source_id TEXT,
    ADD COLUMN IF NOT EXISTS content_hash CHAR(64),
    ADD COLUMN IF NOT EXISTS indexed_at TIMESTAMPTZ;

-- Classify vectors imported before incremental indexing was introduced.
UPDATE public.rag_hr_embeddings
SET source_type = 'legacy_hr',
    source_id = embedding_id::text,
    indexed_at = COALESCE(indexed_at, NOW())
WHERE source_type IS NULL;

UPDATE public.rag_job_embeddings
SET source_type = 'legacy_job',
    source_id = embedding_id::text,
    indexed_at = COALESCE(indexed_at, NOW())
WHERE source_type IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_rag_hr_source
    ON public.rag_hr_embeddings (source_type, source_id)
    WHERE source_type IS NOT NULL AND source_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_rag_job_source
    ON public.rag_job_embeddings (source_type, source_id)
    WHERE source_type IS NOT NULL AND source_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_rag_job_content_hash
    ON public.rag_job_embeddings (content_hash);

CREATE INDEX IF NOT EXISTS idx_rag_job_source_type
    ON public.rag_job_embeddings (source_type);

CREATE TABLE IF NOT EXISTS public.rag_sync_runs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at    TIMESTAMPTZ,
    status          VARCHAR(24) NOT NULL,
    added_count     INTEGER NOT NULL DEFAULT 0,
    updated_count   INTEGER NOT NULL DEFAULT 0,
    unchanged_count INTEGER NOT NULL DEFAULT 0,
    deleted_count   INTEGER NOT NULL DEFAULT 0,
    error_message   TEXT
);
