export type CompanyPosition = {
   id?: number;
   title: string;
   salary: string;
   workingHours: string;
   description: string;
   skills: string[];
};

export type CompanyItem = {
   name: string;
   slug?: string;
   field: string;
   rating: string;
   employees: string;
   location: string;
   openJobs: number;
   color: string;
   bg: string;
   initial: string;
   description: string;
   introduction?: string;
   benefits: string[];
   positions: CompanyPosition[];
   image?: any;
   companyImage?: any;
   contact?: {
      email: string;
      phone: string;
      website: string;
   };
   terms?: string[];
};

export const mockCompanies: CompanyItem[] = [
   { name: "NovaTech", field: "Technology", rating: "4.8", employees: "500-1000", location: "TP. HCM", openJobs: 5, color: "#6366f1", bg: "linear-gradient(135deg, #eef2ff, #e0e7ff)", initial: "N", description: "Công ty phần mềm tập trung vào sản phẩm doanh nghiệp.", introduction: "NovaTech là công ty phần mềm hàng đầu phát triển giải pháp doanh nghiệp với trọng tâm vào quản lý dữ liệu và tự động hóa quy trình. Đội ngũ của NovaTech làm việc trong môi trường sáng tạo, áp dụng công nghệ hiện đại để mang lại sản phẩm ổn định và giá trị lâu dài cho khách hàng.", benefits: ["Thưởng dự án", "BHYT", "Hybrid"], positions: [{ title: "Frontend React Developer", salary: "25–35 triệu", workingHours: "8:00 - 17:00", description: "Phát triển giao diện người dùng với React, TypeScript và Figma. Tham gia vào các dự án web hiện đại.", skills: ["React", "TypeScript", "Figma"] }, { title: "Backend Node.js Engineer", salary: "30–45 triệu", workingHours: "8:00 - 17:00", description: "Xây dựng hệ thống backend với Node.js, MongoDB và Docker. Đảm bảo hiệu suất và bảo mật.", skills: ["Node.js", "MongoDB", "Docker"] }, { title: "Product Owner", salary: "35–50 triệu", workingHours: "9:00 - 18:00", description: "Lãnh đạo roadmap sản phẩm, hợp tác cùng đội kinh doanh và kỹ thuật.", skills: ["Product", "Stakeholder", "Strategy"] }, { title: "QA Automation Engineer", salary: "22–32 triệu", workingHours: "8:30 - 17:30", description: "Thiết kế kịch bản kiểm thử tự động cho sản phẩm nội bộ.", skills: ["Testing", "Selenium", "Automation"] }, { title: "UI Engineer", salary: "24–34 triệu", workingHours: "9:00 - 18:00", description: "Xây dựng hệ thống component và thiết kế tương tác trong thư viện UI.", skills: ["HTML", "CSS", "React"] }] },
   { name: "TechSolutions", field: "Technology", rating: "4.6", employees: "200-500", location: "Hà Nội", openJobs: 4, color: "#6366f1", bg: "linear-gradient(135deg, #eef2ff, #e0e7ff)", initial: "T", description: "Giải pháp công nghệ toàn diện cho doanh nghiệp.", introduction: "TechSolutions cung cấp hệ thống kỹ thuật tích hợp và dịch vụ chuyển đổi số cho doanh nghiệp vừa và lớn. Công ty đặt trọng tâm vào tư vấn chiến lược, phát triển giải pháp tùy chỉnh và hỗ trợ vận hành ổn định, giúp khách hàng tối ưu hóa hiệu suất và tăng tốc câu chuyện số.", benefits: ["Đào tạo", "Remote", "Thưởng"], positions: [{ title: "Software Engineer", salary: "28–40 triệu", workingHours: "9:00 - 18:00", description: "Phát triển phần mềm và ứng dụng.", skills: ["Java", "Spring", "Microservices"] }, { title: "DevOps Specialist", salary: "32–45 triệu", workingHours: "9:00 - 18:00", description: "Quản lý hạ tầng và triển khai.", skills: ["AWS", "Docker", "CI/CD"] }, { title: "Technical Project Manager", salary: "38–52 triệu", workingHours: "9:00 - 18:00", description: "Điều phối dự án và đảm bảo tiến độ giao hàng.", skills: ["PM", "Communication", "Agile"] }, { title: "Cloud Architect", salary: "40–55 triệu", workingHours: "9:00 - 18:00", description: "Thiết kế kiến trúc cloud cho giải pháp doanh nghiệp.", skills: ["Cloud", "Architecture", "Security"] }] },
   { name: "GreenRetail", field: "Ecommerce", rating: "4.5", employees: "200-500", location: "Hà Nội", openJobs: 3, color: "#10b981", bg: "linear-gradient(135deg, #ecfdf5, #d1fae5)", initial: "G", description: "Nền tảng thương mại điện tử và bán lẻ đa kênh.", introduction: "GreenRetail phát triển nền tảng thương mại điện tử xanh và kết nối trực tiếp giữa nhà bán lẻ với người tiêu dùng. Công ty chú trọng logistics hiệu quả, trải nghiệm mua sắm thân thiện và giải pháp bền vững cho ngành bán lẻ hiện đại.", benefits: ["Phụ cấp ăn uống", "Thưởng KPI", "Nghỉ linh hoạt"], positions: [{ title: "Ecommerce Manager", salary: "20–30 triệu", workingHours: "9:00 - 18:00", description: "Quản lý gian hàng và tăng trưởng doanh thu.", skills: ["Ecommerce", "Marketing", "Analytics"] }, { title: "CSKH", salary: "12–18 triệu", workingHours: "9:00 - 18:00", description: "Hỗ trợ khách hàng và xử lý đơn hàng.", skills: ["Giao tiếp", "CSKH", "Xử lý tình huống"] }, { title: "Digital Merchandiser", salary: "16–24 triệu", workingHours: "9:00 - 18:00", description: "Tối ưu hoá hiển thị sản phẩm và chương trình khuyến mại.", skills: ["Merchandising", "Data", "Visual"] }] },
   { name: "Medigo Labs", field: "Healthcare", rating: "4.7", employees: "100-200", location: "TP. HCM", openJobs: 4, color: "#0ea5e9", bg: "linear-gradient(135deg, #f0f9ff, #bae6fd)", initial: "M", description: "Giải pháp công nghệ cho y tế và chăm sóc sức khỏe.", introduction: "Medigo Labs tạo nên những giải pháp công nghệ thông minh cho lĩnh vực y tế, giúp kết nối dữ liệu bệnh nhân, bác sĩ và hệ thống chăm sóc sức khỏe. Công ty tập trung vào tính chính xác, bảo mật và trải nghiệm người dùng để cải thiện hiệu quả điều trị và vận hành bệnh viện.", benefits: ["Bảo hiểm", "Remote", "Đào tạo"], positions: [{ title: "HealthTech Developer", salary: "28–40 triệu", workingHours: "8:30 - 17:30", description: "Xây dựng sản phẩm y tế số.", skills: ["React", "API", "Product thinking"] }, { title: "Data Analyst", salary: "20–30 triệu", workingHours: "8:30 - 17:30", description: "Phân tích dữ liệu nghiệp vụ y tế.", skills: ["SQL", "Excel", "Visualization"] }, { title: "Clinical Product Manager", salary: "32–45 triệu", workingHours: "9:00 - 18:00", description: "Phát triển sản phẩm phục vụ chăm sóc sức khỏe.", skills: ["Product", "Healthcare", "Research"] }, { title: "Medical Software Tester", salary: "18–26 triệu", workingHours: "8:30 - 17:30", description: "Kiểm thử và đánh giá phần mềm y tế.", skills: ["Testing", "Quality", "Healthcare"] }] },
   { name: "HealthCare Plus", field: "Healthcare", rating: "4.8", employees: "300-600", location: "Hà Nội", openJobs: 4, color: "#0ea5e9", bg: "linear-gradient(135deg, #f0f9ff, #bae6fd)", initial: "H", description: "Dịch vụ chăm sóc sức khỏe toàn diện.", introduction: "HealthCare Plus cung cấp hệ sinh thái chăm sóc sức khỏe toàn diện với bệnh viện, phòng khám và các dịch vụ chăm sóc tại nhà. Công ty hoạt động với tinh thần nhân văn và chú trọng đào tạo chuyên môn, giúp người lao động phát triển bền vững trong ngành y tế.", benefits: ["Bảo hiểm y tế", "Đào tạo", "Phụ cấp"], positions: [{ title: "Healthcare Administrator", salary: "18–28 triệu", workingHours: "8:00 - 17:00", description: "Điều phối vận hành y tế và quy trình hành chính.", skills: ["Admin", "Healthcare", "Coordination"] }, { title: "Clinical Support", salary: "15–22 triệu", workingHours: "8:00 - 17:00", description: "Hỗ trợ chuyên môn và hồ sơ bệnh nhân.", skills: ["Patient care", "Documentation", "Communication"] }, { title: "Medical Billing Specialist", salary: "17–24 triệu", workingHours: "8:00 - 17:00", description: "Xử lý hóa đơn và thanh toán bảo hiểm.", skills: ["Billing", "Attention to detail", "Healthcare"] }, { title: "Care Coordinator", salary: "16–23 triệu", workingHours: "8:00 - 17:00", description: "Điều phối dịch vụ chăm sóc cho bệnh nhân.", skills: ["Coordination", "Customer service", "Healthcare"] }] },
   { name: "Finverse", field: "Finance", rating: "4.6", employees: "1000+", location: "Đà Nẵng", openJobs: 5, color: "#f59e0b", bg: "linear-gradient(135deg, #fffbeb, #fde68a)", initial: "F", description: "Dịch vụ tài chính số và quản lý tài sản cá nhân.", benefits: ["Lương cao", "Thưởng", "Phụ cấp công nghệ"], positions: [{ title: "Fintech Analyst", salary: "25–35 triệu", workingHours: "8:00 - 17:00", description: "Phân tích nghiệp vụ tài chính và dữ liệu.", skills: ["Finance", "Data", "SQL"] }, { title: "Product Manager", salary: "35–50 triệu", workingHours: "8:00 - 17:00", description: "Quản lý roadmap và phối hợp đa phòng ban.", skills: ["Product", "Strategy", "Communication"] }, { title: "Risk Analyst", salary: "28–38 triệu", workingHours: "8:00 - 17:00", description: "Đánh giá rủi ro tín dụng và quy trình tuân thủ.", skills: ["Risk", "Analysis", "Regulations"] }, { title: "Wealth Advisor", salary: "30–45 triệu", workingHours: "9:00 - 18:00", description: "Tư vấn đầu tư cá nhân và kế hoạch tài chính.", skills: ["Advisory", "Finance", "Sales"] }, { title: "Data Engineer", salary: "32–45 triệu", workingHours: "8:00 - 17:00", description: "Xây dựng pipeline dữ liệu cho sản phẩm tài chính.", skills: ["Python", "ETL", "Big Data"] }] },
   { name: "BluePixel", field: "Design", rating: "4.9", employees: "50-100", location: "Hà Nội", openJobs: 4, color: "#ec4899", bg: "linear-gradient(135deg, #fce7f3, #fbcfe8)", initial: "B", description: "Agency thiết kế sáng tạo và trải nghiệm số.", benefits: ["Sáng tạo", "Workshop", "Thiết bị tốt"], positions: [{ title: "UI/UX Designer", salary: "18–28 triệu", workingHours: "9:00 - 18:00", description: "Thiết kế giao diện và trải nghiệm người dùng cho ứng dụng di động và web.", skills: ["Figma", "Prototyping", "User Research"] }, { title: "Motion Designer", salary: "20–30 triệu", workingHours: "9:00 - 18:00", description: "Thiết kế chuyển động và visual.", skills: ["After Effects", "Animation", "Creativity"] }, { title: "Brand Designer", salary: "22–32 triệu", workingHours: "9:00 - 18:00", description: "Xây dựng hệ thống nhận diện thương hiệu.", skills: ["Brand", "Illustration", "Typography"] }, { title: "Design Researcher", salary: "19–27 triệu", workingHours: "9:00 - 18:00", description: "Nghiên cứu người dùng và xu hướng thiết kế.", skills: ["Research", "UX", "Interview"] }] },
   { name: "ScaleHub", field: "Technology", rating: "4.4", employees: "300-500", location: "Đà Nẵng", openJobs: 4, color: "#6366f1", bg: "linear-gradient(135deg, #eef2ff, #e0e7ff)", initial: "S", description: "Dịch vụ cloud, hạ tầng và DevOps.", benefits: ["Remote", "Phụ cấp công nghệ", "Đội ngũ trẻ"], positions: [{ title: "DevOps Engineer", salary: "30–45 triệu", workingHours: "8:30 - 17:30", description: "Triển khai hạ tầng và CI/CD.", skills: ["Docker", "Kubernetes", "AWS"] }, { title: "Backend Node.js Engineer", salary: "30–45 triệu", workingHours: "8:30 - 17:30", description: "Xây dựng hệ thống backend với Node.js, MongoDB và Docker.", skills: ["Node.js", "MongoDB", "Docker"] }, { title: "Cloud Support Engineer", salary: "22–30 triệu", workingHours: "8:30 - 17:30", description: "Hỗ trợ khách hàng sử dụng dịch vụ cloud.", skills: ["Linux", "Networking", "Support"] }, { title: "Security Engineer", salary: "35–48 triệu", workingHours: "8:30 - 17:30", description: "Giám sát bảo mật đám mây và kiểm thử thâm nhập.", skills: ["Security", "AWS", "Monitoring"] }] },
   { name: "DataMind", field: "Technology", rating: "4.7", employees: "150-300", location: "TP. HCM", openJobs: 4, color: "#6366f1", bg: "linear-gradient(135deg, #eef2ff, #e0e7ff)", initial: "D", description: "AI và phân tích dữ liệu cho doanh nghiệp.", benefits: ["Nghiên cứu", "Sáng tạo", "Đào tạo AI"], positions: [{ title: "Data Scientist", salary: "35–50 triệu", workingHours: "9:00 - 18:00", description: "Xây dựng mô hình dữ liệu.", skills: ["Python", "ML", "Statistics"] }, { title: "ML Engineer", salary: "40–55 triệu", workingHours: "9:00 - 18:00", description: "Đưa mô hình học máy vào thực tế.", skills: ["TensorFlow", "MLOps", "Deployment"] }, { title: "Data Engineer", salary: "32–45 triệu", workingHours: "9:00 - 18:00", description: "Thiết kế pipeline dữ liệu và ETL.", skills: ["Python", "ETL", "Data Warehousing"] }, { title: "Business Intelligence Analyst", salary: "28–38 triệu", workingHours: "9:00 - 18:00", description: "Xây dựng báo cáo và dashboard quản trị.", skills: ["BI", "SQL", "Visualization"] }] },
   { name: "EduTech Pro", field: "Education", rating: "4.6", employees: "100-200", location: "Hà Nội", openJobs: 3, color: "#06b6d4", bg: "linear-gradient(135deg, #ecfeff, #cffafe)", initial: "E", description: "Nền tảng giáo dục trực tuyến.", benefits: ["Học tập", "Team building", "Thưởng"], positions: [{ title: "Content Creator", salary: "15–22 triệu", workingHours: "8:00 - 17:00", description: "Sản xuất nội dung học tập.", skills: ["Content", "Research", "Writing"] }, { title: "Platform Coordinator", salary: "14–20 triệu", workingHours: "8:00 - 17:00", description: "Điều phối lớp và hỗ trợ vận hành.", skills: ["Planning", "Communication", "Operations"] }, { title: "Learning Experience Designer", salary: "18–26 triệu", workingHours: "8:00 - 17:00", description: "Thiết kế trải nghiệm học trực tuyến.", skills: ["Instructional design", "UX", "Education"] }] },
   { name: "GameForge", field: "Gaming", rating: "4.8", employees: "200-400", location: "TP. HCM", openJobs: 4, color: "#dc2626", bg: "linear-gradient(135deg, #fef2f2, #fee2e2)", initial: "G", description: "Phát triển game mobile và PC.", benefits: ["Sáng tạo", "Thưởng game", "Môi trường vui"], positions: [{ title: "Game Developer", salary: "25–40 triệu", workingHours: "9:00 - 18:00", description: "Lập trình gameplay.", skills: ["Unity", "C#", "Game logic"] }, { title: "Game Designer", salary: "20–35 triệu", workingHours: "9:00 - 18:00", description: "Thiết kế cơ chế và trải nghiệm.", skills: ["Game Design", "Balance", "Creativity"] }, { title: "QA Tester", salary: "18–26 triệu", workingHours: "9:00 - 18:00", description: "Kiểm thử game và báo lỗi.", skills: ["Testing", "Attention to detail", "Game mechanics"] }, { title: "Level Designer", salary: "22–32 triệu", workingHours: "9:00 - 18:00", description: "Thiết kế cấp độ và thử nghiệm trải nghiệm.", skills: ["Level design", "Creativity", "Gameplay"] }] },
   { name: "LogiChain", field: "Logistics", rating: "4.3", employees: "500-1000", location: "Đà Nẵng", openJobs: 4, color: "#059669", bg: "linear-gradient(135deg, #ecfdf5, #d1fae5)", initial: "L", description: "Giải pháp logistics và kho vận.", benefits: ["Ổn định", "Phụ cấp", "Đào tạo"], positions: [{ title: "Logistics Coordinator", salary: "15–25 triệu", workingHours: "7:00 - 16:00", description: "Điều phối hàng hóa và vận chuyển.", skills: ["Supply Chain", "Excel", "Coordination"] }, { title: "Warehouse Supervisor", salary: "18–28 triệu", workingHours: "7:00 - 16:00", description: "Quản lý kho và xuất nhập.", skills: ["Warehouse", "Leadership", "Inventory"] }, { title: "Transport Planner", salary: "16–24 triệu", workingHours: "7:00 - 16:00", description: "Lập kế hoạch vận chuyển hiệu quả.", skills: ["Planning", "Logistics", "Optimization"] }, { title: "Inventory Analyst", salary: "17–25 triệu", workingHours: "7:00 - 16:00", description: "Theo dõi tồn kho và tối ưu mặt bằng kho.", skills: ["Inventory", "Data", "Reporting"] }] },
   { name: "TechBuild", field: "Manufacturing", rating: "4.5", employees: "300-600", location: "Bình Dương", openJobs: 3, color: "#7c3aed", bg: "linear-gradient(135deg, #f3e8ff, #e9d5ff)", initial: "T", description: "Sản xuất thiết bị công nghệ cao.", benefits: ["An toàn", "Đào tạo", "Ca đêm"], positions: [{ title: "Manufacturing Engineer", salary: "20–30 triệu", workingHours: "6:00 - 14:00", description: "Tối ưu dây chuyền sản xuất.", skills: ["Lean", "Process", "Technical"] }, { title: "Quality Control Staff", salary: "14–20 triệu", workingHours: "6:00 - 14:00", description: "Kiểm tra chất lượng sản phẩm.", skills: ["QC", "Inspection", "Detail"] }, { title: "Production Planner", salary: "18–26 triệu", workingHours: "6:00 - 14:00", description: "Lập kế hoạch sản xuất và điều phối nguyên liệu.", skills: ["Planning", "Scheduling", "Communication"] }] },
   { name: "ConsultPro", field: "Consulting", rating: "4.9", employees: "50-100", location: "TP. HCM", openJobs: 3, color: "#0891b2", bg: "linear-gradient(135deg, #ecfeff, #cffafe)", initial: "C", description: "Tư vấn chiến lược cho doanh nghiệp.", benefits: ["Lương cao", "Thưởng dự án", "Làm việc linh hoạt"], positions: [{ title: "Business Consultant", salary: "30–50 triệu", workingHours: "8:00 - 17:00", description: "Tư vấn chiến lược và tối ưu hoạt động.", skills: ["Strategy", "Analysis", "Presentation"] }, { title: "Research Analyst", salary: "20–30 triệu", workingHours: "8:00 - 17:00", description: "Nghiên cứu thị trường và báo cáo.", skills: ["Research", "Data", "Reporting"] }, { title: "Client Success Manager", salary: "28–38 triệu", workingHours: "8:00 - 17:00", description: "Quản lý quan hệ khách hàng và phụ trách dự án.", skills: ["Communication", "Project management", "Consulting"] }] },
   { name: "RealEstate Plus", field: "Real Estate", rating: "4.4", employees: "100-250", location: "Hà Nội", openJobs: 4, color: "#ea580c", bg: "linear-gradient(135deg, #fff7ed, #fed7aa)", initial: "R", description: "Phát triển và quản lý dự án bất động sản.", benefits: ["Hoa hồng cao", "Thưởng bán hàng", "Đào tạo"], positions: [{ title: "Real Estate Agent", salary: "20–40 triệu", workingHours: "8:00 - 17:00", description: "Tư vấn và chốt giao dịch.", skills: ["Sales", "Negotiation", "Market knowledge"] }, { title: "Project Coordinator", salary: "18–26 triệu", workingHours: "8:00 - 17:00", description: "Điều phối dự án và thủ tục triển khai.", skills: ["Coordination", "Planning", "Documentation"] }, { title: "Property Marketing Specialist", salary: "19–28 triệu", workingHours: "8:00 - 17:00", description: "Xây dựng chiến dịch marketing cho dự án BĐS.", skills: ["Marketing", "Content", "Real estate"] }, { title: "Customer Relations Officer", salary: "16–24 triệu", workingHours: "8:00 - 17:00", description: "Chăm sóc khách hàng và hỗ trợ giao dịch.", skills: ["Customer service", "Communication", "Sales"] }] },
   { name: "AutoTech", field: "Automotive", rating: "4.6", employees: "400-800", location: "Vĩnh Phúc", openJobs: 3, color: "#dc2626", bg: "linear-gradient(135deg, #fef2f2, #fee2e2)", initial: "A", description: "Sản xuất và lắp ráp xe hơi.", benefits: ["Lương ngành", "Bảo hiểm", "Kỹ thuật"], positions: [{ title: "Automotive Engineer", salary: "25–40 triệu", workingHours: "7:30 - 16:30", description: "Thiết kế và cải tiến bộ phận xe.", skills: ["Engineering", "AutoCAD", "Testing"] }, { title: "Assembly Supervisor", salary: "18–28 triệu", workingHours: "7:30 - 16:30", description: "Giám sát dây chuyền lắp ráp.", skills: ["Manufacturing", "Leadership", "QC"] }, { title: "Service Technician", salary: "17–26 triệu", workingHours: "7:30 - 16:30", description: "Bảo trì và sửa chữa hệ thống xe.", skills: ["Mechanical", "Diagnostics", "Repair"] }] },
   { name: "FoodTech", field: "Food & Beverage", rating: "4.5", employees: "200-400", location: "TP. HCM", openJobs: 3, color: "#16a34a", bg: "linear-gradient(135deg, #f0fdf4, #dcfce7)", initial: "F", description: "Nền tảng giao thực phẩm và ẩm thực số.", benefits: ["Ăn uống", "Hiệu suất", "Vui vẻ"], positions: [{ title: "Product Operations", salary: "18–28 triệu", workingHours: "9:00 - 18:00", description: "Vận hành sản phẩm và theo dõi hiệu suất.", skills: ["Operations", "Reporting", "Process"] }, { title: "Partnership Executive", salary: "20–30 triệu", workingHours: "9:00 - 18:00", description: "Phát triển đối tác nhà hàng.", skills: ["Negotiation", "Communication", "Sales"] }, { title: "Customer Success", salary: "15–22 triệu", workingHours: "9:00 - 18:00", description: "Hỗ trợ khách hàng và xử lý phản hồi.", skills: ["Service", "Communication", "Problem solving"] }] },
   { name: "MediCare", field: "Healthcare", rating: "4.8", employees: "300-600", location: "Hà Nội", openJobs: 3, color: "#be123c", bg: "linear-gradient(135deg, #fdf2f8, #fce7f3)", initial: "M", description: "Dịch vụ chăm sóc sức khỏe toàn diện.", benefits: ["Bảo hiểm y tế", "Phụ cấp chuyên môn", "Nhân văn"], positions: [{ title: "Healthcare Administrator", salary: "18–28 triệu", workingHours: "8:00 - 17:00", description: "Điều phối vận hành y tế.", skills: ["Admin", "Healthcare", "Coordination"] }, { title: "Clinical Support", salary: "15–22 triệu", workingHours: "8:00 - 17:00", description: "Hỗ trợ chuyên môn và hồ sơ bệnh nhân.", skills: ["Patient care", "Documentation", "Communication"] }, { title: "Health Educator", salary: "16–24 triệu", workingHours: "8:00 - 17:00", description: "Tư vấn cải thiện sức khỏe cho bệnh nhân.", skills: ["Education", "Communication", "Healthcare"] }] },
   { name: "TravelGo", field: "Travel", rating: "4.7", employees: "150-300", location: "Đà Nẵng", openJobs: 3, color: "#0d9488", bg: "linear-gradient(135deg, #f0fdfa, #ccfbf1)", initial: "T", description: "Dịch vụ du lịch trực tuyến.", benefits: ["Du lịch", "Booking", "Đào tạo"], positions: [{ title: "Travel Consultant", salary: "15–25 triệu", workingHours: "8:00 - 17:00", description: "Tư vấn tour và vé.", skills: ["Sales", "Customer service", "Travel knowledge"] }, { title: "Tour Coordinator", salary: "16–24 triệu", workingHours: "8:00 - 17:00", description: "Điều phối lịch trình tour.", skills: ["Planning", "Communication", "Operations"] }, { title: "Marketing Specialist", salary: "18–26 triệu", workingHours: "8:00 - 17:00", description: "Quảng bá tour và gói du lịch.", skills: ["Marketing", "Social media", "Copywriting"] }] },
   { name: "EnergyCorp", field: "Energy", rating: "4.4", employees: "500-1000", location: "Hải Phòng", openJobs: 4, color: "#ca8a04", bg: "linear-gradient(135deg, #fefce8, #fef08a)", initial: "E", description: "Năng lượng tái tạo và giải pháp xanh.", benefits: ["Xanh", "An toàn", "Quốc tế"], positions: [{ title: "Energy Engineer", salary: "30–45 triệu", workingHours: "7:00 - 16:00", description: "Thiết kế và vận hành hệ thống năng lượng.", skills: ["Electrical", "Renewable", "Engineering"] }, { title: "Project Technician", salary: "18–26 triệu", workingHours: "7:00 - 16:00", description: "Hỗ trợ triển khai dự án năng lượng.", skills: ["Technical", "Site work", "Maintenance"] }, { title: "Sustainability Analyst", salary: "24–34 triệu", workingHours: "7:00 - 16:00", description: "Đánh giá hiệu quả xanh và báo cáo.", skills: ["Sustainability", "Analysis", "Reporting"] }, { title: "Field Coordinator", salary: "20–28 triệu", workingHours: "7:00 - 16:00", description: "Giám sát triển khai tại công trường.", skills: ["Coordination", "Safety", "Operations"] }] },
   { name: "FashionHub", field: "Fashion", rating: "4.6", employees: "100-250", location: "TP. HCM", openJobs: 3, color: "#db2777", bg: "linear-gradient(135deg, #fdf2f8, #fce7f3)", initial: "F", description: "Thiết kế và sản xuất thời trang hiện đại.", benefits: ["Sáng tạo", "Thưởng thiết kế", "Thời trang"], positions: [{ title: "Fashion Designer", salary: "20–35 triệu", workingHours: "9:00 - 18:00", description: "Thiết kế bộ sưu tập và phối hợp sản xuất.", skills: ["Design", "Trend analysis", "Illustration"] }, { title: "Merchandiser", salary: "18–26 triệu", workingHours: "9:00 - 18:00", description: "Quản lý sản phẩm và chuỗi cung ứng.", skills: ["Product", "Coordination", "Retail"] }, { title: "Visual Merchandiser", salary: "19–27 triệu", workingHours: "9:00 - 18:00", description: "Trang trí và trưng bày sản phẩm.", skills: ["Visual", "Display", "Style"] }] },
   { name: "AgriTech", field: "Agriculture", rating: "4.3", employees: "200-400", location: "Cần Thơ", openJobs: 3, color: "#65a30d", bg: "linear-gradient(135deg, #f7fee7, #ecfccb)", initial: "A", description: "Ứng dụng công nghệ vào nông nghiệp.", benefits: ["Thiên nhiên", "Thưởng mùa vụ", "Đào tạo"], positions: [{ title: "AgriTech Specialist", salary: "18–30 triệu", workingHours: "7:00 - 16:00", description: "Triển khai công nghệ hỗ trợ nông nghiệp.", skills: ["Agriculture", "IoT", "Field support"] }, { title: "Field Operations", salary: "14–22 triệu", workingHours: "7:00 - 16:00", description: "Theo dõi thực địa và hỗ trợ nông dân.", skills: ["Operations", "Communication", "On-site"] }, { title: "Agriculture Analyst", salary: "20–28 triệu", workingHours: "7:00 - 16:00", description: "Phân tích dữ liệu nông nghiệp và hiệu suất mùa vụ.", skills: ["Data", "Agriculture", "Reporting"] }] },
   { name: "InnovateTech", field: "Technology", rating: "4.9", employees: "100-200", location: "Hà Nội", openJobs: 3, color: "#6366f1", bg: "linear-gradient(135deg, #eef2ff, #e0e7ff)", initial: "I", description: "Công ty công nghệ đổi mới với AI và machine learning.", benefits: ["Đổi mới", "Thưởng sáng tạo", "Remote"], positions: [{ title: "AI Researcher", salary: "40–60 triệu", workingHours: "9:00 - 18:00", description: "Nghiên cứu và phát triển AI.", skills: ["Python", "TensorFlow", "Research"] }, { title: "Machine Learning Engineer", salary: "35–50 triệu", workingHours: "9:00 - 18:00", description: "Triển khai mô hình ML.", skills: ["ML", "Deployment", "Cloud"] }, { title: "AI Product Manager", salary: "38–52 triệu", workingHours: "9:00 - 18:00", description: "Quản lý sản phẩm AI và roadmap.", skills: ["Product", "AI", "Strategy"] }] },
   { name: "ShopEase", field: "Ecommerce", rating: "4.7", employees: "50-100", location: "TP. HCM", openJobs: 3, color: "#10b981", bg: "linear-gradient(135deg, #ecfdf5, #d1fae5)", initial: "S", description: "Nền tảng thương mại điện tử dễ sử dụng.", benefits: ["Thưởng doanh số", "Đào tạo", "Linh hoạt"], positions: [{ title: "Ecommerce Specialist", salary: "18–25 triệu", workingHours: "8:00 - 17:00", description: "Quản lý cửa hàng trực tuyến.", skills: ["Ecommerce", "SEO", "Marketing"] }, { title: "Customer Experience Lead", salary: "19–28 triệu", workingHours: "8:00 - 17:00", description: "Cải thiện trải nghiệm khách hàng.", skills: ["CX", "Service", "Analytics"] }, { title: "Growth Marketing", salary: "20–30 triệu", workingHours: "8:00 - 17:00", description: "Tăng trưởng người dùng và chuyển đổi.", skills: ["Marketing", "Analytics", "Growth"] }] },
   { name: "BioHealth", field: "Healthcare", rating: "4.9", employees: "100-200", location: "Đà Nẵng", openJobs: 3, color: "#0ea5e9", bg: "linear-gradient(135deg, #f0f9ff, #bae6fd)", initial: "B", description: "Công nghệ sinh học cho sức khỏe.", benefits: ["Nghiên cứu", "Đào tạo", "Bảo hiểm"], positions: [{ title: "Biotech Researcher", salary: "30–45 triệu", workingHours: "8:00 - 17:00", description: "Nghiên cứu công nghệ sinh học.", skills: ["Biology", "Research", "Lab work"] }, { title: "Clinical Data Specialist", salary: "28–38 triệu", workingHours: "8:00 - 17:00", description: "Quản lý dữ liệu thử nghiệm lâm sàng.", skills: ["Data", "Healthcare", "Compliance"] }, { title: "Lab Technician", salary: "18–26 triệu", workingHours: "8:00 - 17:00", description: "Hỗ trợ thí nghiệm và phân tích mẫu.", skills: ["Lab work", "Attention to detail", "Protocol"] }] },
   { name: "UrbanDesign", field: "Design", rating: "4.8", employees: "30-50", location: "Hà Nội", openJobs: 3, color: "#ec4899", bg: "linear-gradient(135deg, #fce7f3, #fbcfe8)", initial: "U", description: "Thiết kế đô thị và kiến trúc.", benefits: ["Sáng tạo", "Workshop", "Thiết bị"], positions: [{ title: "Urban Designer", salary: "22–32 triệu", workingHours: "9:00 - 18:00", description: "Thiết kế không gian đô thị.", skills: ["Architecture", "Planning", "Design"] }, { title: "Landscape Architect", salary: "24–34 triệu", workingHours: "9:00 - 18:00", description: "Thiết kế cảnh quan và không gian xanh.", skills: ["Landscape", "Design", "Planning"] }, { title: "Architectural Illustrator", salary: "20–28 triệu", workingHours: "9:00 - 18:00", description: "Minh hoạ dự án và trình bày thiết kế.", skills: ["Illustration", "Rendering", "Presentation"] }] },
   { name: "EduFuture", field: "Education", rating: "4.7", employees: "80-150", location: "TP. HCM", openJobs: 3, color: "#06b6d4", bg: "linear-gradient(135deg, #ecfeff, #cffafe)", initial: "E", description: "Giáo dục tương lai với công nghệ.", benefits: ["Học tập", "Đào tạo", "Thưởng"], positions: [{ title: "EdTech Developer", salary: "25–35 triệu", workingHours: "8:00 - 17:00", description: "Phát triển nền tảng giáo dục.", skills: ["EdTech", "Development", "Education"] }, { title: "Learning Experience Designer", salary: "18–26 triệu", workingHours: "8:00 - 17:00", description: "Thiết kế trải nghiệm học tập.", skills: ["Instructional design", "UX", "Education"] }, { title: "Student Success Coordinator", salary: "15–22 triệu", workingHours: "8:00 - 17:00", description: "Hỗ trợ sinh viên và theo dõi tiến độ học tập.", skills: ["Support", "Communication", "Coaching"] }] },
   { name: "GameWorld", field: "Gaming", rating: "4.9", employees: "150-250", location: "Đà Nẵng", openJobs: 3, color: "#dc2626", bg: "linear-gradient(135deg, #fef2f2, #fee2e2)", initial: "G", description: "Thế giới game sáng tạo.", benefits: ["Sáng tạo", "Thưởng game", "Môi trường vui"], positions: [{ title: "Game Artist", salary: "20–30 triệu", workingHours: "9:00 - 18:00", description: "Thiết kế nghệ thuật cho game.", skills: ["Art", "Game Design", "Creativity"] }, { title: "Level Designer", salary: "22–32 triệu", workingHours: "9:00 - 18:00", description: "Thiết kế cấp độ và trải nghiệm.", skills: ["Level design", "Creativity", "Gameplay"] }, { title: "Gameplay Programmer", salary: "28–40 triệu", workingHours: "9:00 - 18:00", description: "Lập trình cơ chế chơi và logic game.", skills: ["C#", "Unity", "Game logic"] }] },
   { name: "SparkWorks", field: "Technology", rating: "4.6", employees: "120-220", location: "Hà Nội", openJobs: 3, color: "#6366f1", bg: "linear-gradient(135deg, #eef2ff, #e0e7ff)", initial: "S", description: "Công ty công nghệ đổi mới với sản phẩm SaaS.", benefits: ["Remote", "Thưởng sáng tạo", "Đào tạo"], positions: [{ title: "Software Architect", salary: "35–50 triệu", workingHours: "9:00 - 18:00", description: "Thiết kế kiến trúc hệ thống SaaS.", skills: ["Architecture", "Cloud", "Microservices"] }, { title: "QA Engineer", salary: "22–30 triệu", workingHours: "9:00 - 18:00", description: "Đảm bảo chất lượng ứng dụng và tự động hóa kiểm thử.", skills: ["Testing", "Selenium", "Automation"] }, { title: "Customer Success Engineer", salary: "28–38 triệu", workingHours: "9:00 - 18:00", description: "Hỗ trợ khách hàng triển khai SaaS.", skills: ["Support", "Cloud", "Communication"] }] },
   { name: "GreenFoods", field: "Food & Beverage", rating: "4.6", employees: "100-180", location: "TP. HCM", openJobs: 3, color: "#16a34a", bg: "linear-gradient(135deg, #f0fdf4, #dcfce7)", initial: "G", description: "Chuỗi thực phẩm xanh và phân phối tech-driven.", benefits: ["Ăn uống", "Linh hoạt", "Đào tạo"], positions: [{ title: "Food Operations Lead", salary: "22–32 triệu", workingHours: "8:00 - 17:00", description: "Quản lý hoạt động chuỗi cung ứng thực phẩm.", skills: ["Operations", "Logistics", "Food safety"] }, { title: "Supply Chain Specialist", salary: "20–28 triệu", workingHours: "8:00 - 17:00", description: "Tối ưu chuỗi cung ứng và logistics.", skills: ["Supply Chain", "Planning", "Analytics"] }, { title: "Quality Assurance Coordinator", salary: "18–26 triệu", workingHours: "8:00 - 17:00", description: "Giám sát an toàn và chất lượng thực phẩm.", skills: ["QA", "Food safety", "Inspection"] }] },
];
