const exactTitleMap: Record<string, string> = {
   "Frontend React Developer": "Lập trình viên Frontend React",
   "Backend Node.js Engineer": "Kỹ sư Backend Node.js",
   "UI/UX Designer": "Nhà thiết kế UI/UX",
   "Software Engineer": "Kỹ sư phần mềm",
   "DevOps Specialist": "Chuyên viên DevOps",
   "Technical Project Manager": "Quản lý dự án kỹ thuật",
   "Cloud Architect": "Kiến trúc sư Cloud",
   "Ecommerce Manager": "Quản lý thương mại điện tử",
   "Data Analyst": "Chuyên viên phân tích dữ liệu",
   "Product Manager": "Quản lý sản phẩm",
   "Risk Analyst": "Chuyên viên phân tích rủi ro",
   "Data Scientist": "Nhà khoa học dữ liệu",
   "ML Engineer": "Kỹ sư học máy",
   "Business Intelligence Analyst": "Chuyên viên phân tích BI",
   "Game Developer": "Lập trình viên game",
   "Game Designer": "Nhà thiết kế game",
   "QA Engineer": "Kỹ sư kiểm thử",
   "Brand Designer": "Nhà thiết kế thương hiệu",
   "Research Analyst": "Chuyên viên phân tích nghiên cứu",
   "Business Consultant": "Chuyên viên tư vấn doanh nghiệp",
   "Customer Relations Officer": "Nhân viên quan hệ khách hàng",
   "Real Estate Agent": "Nhân viên kinh doanh bất động sản",
   "Healthcare Administrator": "Quản trị viên y tế",
   "Clinical Support": "Nhân viên hỗ trợ lâm sàng",
   "Medical Billing Specialist": "Chuyên viên thanh toán y tế",
   "Care Coordinator": "Điều phối viên chăm sóc",
   "Customer Success": "Nhân viên chăm sóc khách hàng",
   "Customer Success Engineer": "Kỹ sư hỗ trợ khách hàng",
   "Product Operations": "Chuyên viên vận hành sản phẩm",
   "Field Operations": "Nhân viên vận hành hiện trường",
   "Supply Chain Specialist": "Chuyên viên chuỗi cung ứng",
   "Content Creator": "Nhân viên sáng tạo nội dung",
   "Growth Marketing": "Chuyên viên tăng trưởng marketing",
   "Product Owner": "Quản lý sản phẩm",
   "QA Automation Engineer": "Kỹ sư kiểm thử tự động",
   "UI Engineer": "Kỹ sư giao diện người dùng",
   "DevOps Engineer": "Kỹ sư vận hành hệ thống",
   "Cloud Support Engineer": "Kỹ sư hỗ trợ điện toán đám mây",
   "Security Engineer": "Kỹ sư an ninh hệ thống",
   "Learning Experience Designer": "Nhà thiết kế trải nghiệm học tập",
   "Platform Coordinator": "Điều phối viên nền tảng",
   "Game Artist": "Họa sĩ thiết kế game",
   "Gameplay Programmer": "Lập trình viên lối chơi",
   "Level Designer": "Nhà thiết kế màn chơi",
   "Ecommerce Specialist": "Chuyên viên thương mại điện tử",
   "Partnership Executive": "Chuyên viên phát triển đối tác",
   "Warehouse Supervisor": "Giám sát kho vận",
   "Logistics Coordinator": "Điều phối viên logistics",
   "Transport Planner": "Chuyên viên lập kế hoạch vận tải",
   "Inventory Analyst": "Chuyên viên phân tích tồn kho",
   "Manufacturing Engineer": "Kỹ sư sản xuất",
   "Quality Control Staff": "Nhân viên kiểm soát chất lượng",
   "Production Planner": "Chuyên viên lập kế hoạch sản xuất",
   "Service Technician": "Kỹ thuật viên dịch vụ",
   "Medical Software Tester": "Nhân viên kiểm thử phần mềm y tế",
   "Clinical Product Manager": "Quản lý sản phẩm lâm sàng",
   "HealthTech Developer": "Lập trình viên công nghệ y tế",
   "EdTech Developer": "Lập trình viên công nghệ giáo dục",
   "Travel Consultant": "Tư vấn viên du lịch",
   "Tour Coordinator": "Điều phối viên tour",
   "Marketing Specialist": "Chuyên viên marketing",
   "Energy Engineer": "Kỹ sư năng lượng",
   "Project Technician": "Kỹ thuật viên dự án",
   "Sustainability Analyst": "Chuyên viên phân tích phát triển bền vững",
   "Field Coordinator": "Điều phối viên hiện trường",
   "Fashion Designer": "Nhà thiết kế thời trang",
   "Merchandiser": "Chuyên viên trưng bày sản phẩm",
   "Visual Merchandiser": "Chuyên viên trưng bày trực quan",
   "AgriTech Specialist": "Chuyên viên công nghệ nông nghiệp",
   "Agriculture Analyst": "Chuyên viên phân tích nông nghiệp",
   "AI Researcher": "Nhà nghiên cứu trí tuệ nhân tạo",
   "Machine Learning Engineer": "Kỹ sư học máy",
   "AI Product Manager": "Quản lý sản phẩm trí tuệ nhân tạo",
   "Biotech Researcher": "Nhà nghiên cứu công nghệ sinh học",
   "Clinical Data Specialist": "Chuyên viên dữ liệu lâm sàng",
   "Lab Technician": "Kỹ thuật viên phòng thí nghiệm",
   "Urban Designer": "Nhà thiết kế đô thị",
   "Landscape Architect": "Kiến trúc sư cảnh quan",
   "Architectural Illustrator": "Họa viên kiến trúc",
   "Software Architect": "Kiến trúc sư phần mềm",
   "Food Operations Lead": "Trưởng nhóm vận hành thực phẩm",
   "Quality Assurance Coordinator": "Điều phối viên đảm bảo chất lượng",
};

const replacementRules: Array<[RegExp, string]> = [
   [/\bFullstack\b/gi, "toàn diện"],
   [/\bFrontend\b/gi, "giao diện"],
   [/\bBackend\b/gi, "hệ thống"],
   [/\bDeveloper\b/gi, "Lập trình viên"],
   [/\bEngineer\b/gi, "Kỹ sư"],
   [/\bManager\b/gi, "Quản lý"],
   [/\bSpecialist\b/gi, "Chuyên viên"],
   [/\bAnalyst\b/gi, "Chuyên viên phân tích"],
   [/\bCoordinator\b/gi, "Điều phối viên"],
   [/\bConsultant\b/gi, "Tư vấn viên"],
   [/\bDesigner\b/gi, "Nhà thiết kế"],
   [/\bArchitect\b/gi, "Kiến trúc sư"],
   [/\bTechnician\b/gi, "Kỹ thuật viên"],
   [/\bAdministrator\b/gi, "Quản trị viên"],
   [/\bOfficer\b/gi, "Nhân viên"],
   [/\bSupport\b/gi, "hỗ trợ"],
   [/\bLead\b/gi, "Trưởng nhóm"],
   [/\bOwner\b/gi, "Quản lý"],
   [/\bResearcher\b/gi, "Nhà nghiên cứu"],
   [/\bProgrammer\b/gi, "Lập trình viên"],
   [/\bScientist\b/gi, "Nhà khoa học"],
   [/\bExecutive\b/gi, "Chuyên viên"],
   [/\bPlanner\b/gi, "Chuyên viên lập kế hoạch"],
   [/\bSupervisor\b/gi, "Giám sát"],
   [/\bStaff\b/gi, "Nhân viên"],
   [/\bOperations\b/gi, "vận hành"],
   [/\bMarketing\b/gi, "tiếp thị"],
   [/\bSoftware\b/gi, "phần mềm"],
   [/\bCloud\b/gi, "điện toán đám mây"],
   [/\bData\b/gi, "dữ liệu"],
   [/\bProduct\b/gi, "sản phẩm"],
   [/\bCustomer\b/gi, "khách hàng"],
   [/\bSuccess\b/gi, "thành công"],
   [/\bGame\b/gi, "trò chơi"],
   [/\bTravel\b/gi, "du lịch"],
   [/\bEnergy\b/gi, "năng lượng"],
   [/\bFashion\b/gi, "thời trang"],
   [/\bMedical\b/gi, "y tế"],
   [/\bClinical\b/gi, "lâm sàng"],
];

export const toVietnameseJobTitle = (title: string): string => {
   const normalized = title.trim().replace(/\s+/g, " ");
   if (!normalized) {
      return title;
   }

   const exact = exactTitleMap[normalized];
   if (exact) {
      return exact;
   }

   let localized = normalized;
   replacementRules.forEach(([pattern, replacement]) => {
      localized = localized.replace(pattern, replacement);
   });

   return localized
      .replace(/\s{2,}/g, " ")
      .replace(/\s+\//g, "/")
      .replace(/\/+\s+/g, "/")
      .trim();
};
